version: '3.8'

services:
  crab-infinity:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ../../config/state:/app/config/state
    environment:
      - ENV=production
    restart: always
